# Generated by Django 3.0.5 on 2020-09-12 17:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Category')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='slug')),
                ('status', models.BooleanField(default=True, verbose_name='show?')),
                ('position', models.IntegerField(verbose_name='position')),
                ('parent', models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='childeren', to='blog.Category', verbose_name='subText')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('describtion', models.TextField()),
                ('thumbnail', models.ImageField(upload_to='media')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('craeted', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('d', 'Draft'), ('p', 'Publish')], max_length=1)),
                ('category', models.ManyToManyField(related_name='articles', to='blog.Category', verbose_name='categorys')),
            ],
        ),
    ]
