# Generated by Django 3.0.5 on 2020-08-20 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200820_1327'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['position'], 'verbose_name': 'Categorys', 'verbose_name_plural': 'titles'},
        ),
    ]
