# Generated by Django 3.0.5 on 2020-08-20 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200820_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='Category',
            field=models.ManyToManyField(to='blog.Category', verbose_name='categorys'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Category'),
        ),
    ]
